dist: focal
language: python
python:
  - "3.7"
before_install:
  sudo apt-get install python3-dev python3-pip

install:
  pip3 install ue4-docker

script:
  - sudo ue4-docker setup
  - ue4-docker build 4.25.1 --no-engine
  - ue4-docker clean --source
  - ue4 build
  - ue4 package

branches:
  only:
    - develop
    